#!/bin/bash

echo "🚀 CONFİ LED DISPLAY - RENDER DEPLOYMENT SCRIPT"
echo "================================================"
echo ""

echo "✅ Step 1: Code pushed to GitHub ✓"
echo "   Repository: https://github.com/AnshikaTrivedii/Confi_web-app.git"
echo ""

echo "🔧 Step 2: Backend Deployment (FastAPI)"
echo "   Follow these steps on Render.com:"
echo ""
echo "   1. Go to https://render.com and sign up/login"
echo "   2. Click 'New +' → 'Web Service'"
echo "   3. Connect your GitHub repository: AnshikaTrivedii/Confi_web-app"
echo "   4. Configure the service:"
echo "      - Name: confi-backend"
echo "      - Environment: Python 3"
echo "      - Root Directory: backend"
echo "      - Build Command: pip install -r requirements.txt"
echo "      - Start Command: python start_production.py"
echo "   5. Add Environment Variables:"
echo "      - SECRET_KEY: your-super-secret-key-here-make-it-long-and-secure"
echo "      - ALGORITHM: HS256"
echo "      - ACCESS_TOKEN_EXPIRE_MINUTES: 30"
echo "      - REFRESH_TOKEN_EXPIRE_DAYS: 7"
echo "      - ENVIRONMENT: production"
echo "   6. Click 'Create Web Service'"
echo ""

echo "🌐 Step 3: Frontend Deployment (React)"
echo "   Follow these steps on Render.com:"
echo ""
echo "   1. Click 'New +' → 'Static Site'"
echo "   2. Connect your GitHub repository: AnshikaTrivedii/Confi_web-app"
echo "   3. Configure the service:"
echo "      - Name: confi-frontend"
echo "      - Root Directory: confi-web-app"
echo "      - Build Command: npm install && npm run build"
echo "      - Publish Directory: build"
echo "   4. Add Environment Variable:"
echo "      - REACT_APP_API_URL: https://your-backend-url.onrender.com/api/v1"
echo "   5. Click 'Create Static Site'"
echo ""

echo "🔗 Step 4: Update Frontend API URL"
echo "   Once backend is deployed, update the API URL in:"
echo "   confi-web-app/src/services/api.js"
echo "   Change API_BASE_URL to your backend URL"
echo ""

echo "📊 Step 5: Test Your Application"
echo "   - Backend API: https://your-backend-url.onrender.com/docs"
echo "   - Frontend: https://your-frontend-url.onrender.com"
echo ""

echo "🎉 DEPLOYMENT COMPLETE!"
echo "   Your Confi LED Display app will be live on Render!"
echo ""

echo "📝 Quick Commands:"
echo "   - View backend logs: render logs confi-backend"
echo "   - View frontend logs: render logs confi-frontend"
echo "   - Restart services: render restart confi-backend"
echo "" 